name: discord-notification

on:
  pull_request:
    types: [opened, closed]
    branches:
      - stg
      - develop

jobs:
  notify:
    name: Notify Discord
    runs-on: ubuntu-20.04
    steps:
      - name: Notify on Pull Request Open
        if: github.event.action == 'opened'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          name: Discord Notification
          title: ${{ github.event.pull_request.title || 'No Title' }}
          description: |
            Pull Request: ${{ github.event.pull_request.html_url || 'No URL' }}
            Author: ${{ github.event.pull_request.user.login || 'Unknown Author' }}

      - name: Notify on Pull Request Close
        if: github.event.action == 'closed'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.WORKING_TO_DEVELOP_WEBHOOK }}
          name: Discord Notification
          title: ${{ github.event.pull_request.title || 'No Title' }}
          description: |
            Pull Request Closed: ${{ github.event.pull_request.html_url || 'No URL' }}
            Author: ${{ github.event.pull_request.user.login || 'Unknown Author' }}